# Generated by Django 2.2.2 on 2019-07-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20190702_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuecomment',
            old_name='issue',
            new_name='issue_id',
        ),
        migrations.RenameField(
            model_name='issuecomment',
            old_name='user',
            new_name='user_id',
        ),
    ]
