# Generated by Django 2.2.2 on 2019-07-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20190706_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_complete',
            field=models.DateField(null=True),
        ),
    ]
