# Generated by Django 2.2.2 on 2019-07-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_date_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='pending', max_length=11),
        ),
    ]
