# Generated by Django 2.2.2 on 2019-07-18 21:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20190717_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
