# Generated by Django 2.2.2 on 2019-07-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20190718_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
