# Generated by Django 2.2.2 on 2019-07-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_auto_20190726_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='amount_paid',
            new_name='total_paid',
        ),
    ]
