dist: xenial
language: python
python:
    - "3.7"
install: "pip install -r requirements.txt"

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres

script:
  - python manage.py test
