# Generated by Django 2.2.2 on 2019-07-29 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_auto_20190729_2218'),
        ('checkout', '0009_auto_20190726_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='issue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='issues.Issue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='request_type',
            field=models.CharField(default='new request', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checkout.Order'),
        ),
    ]
