# Generated by Django 2.2.2 on 2019-07-21 21:00

import cart.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0011_auto_20190719_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('request_type', models.CharField(choices=[('new feature', 'New Feature'), ('feature vote', 'Feature Vote')], max_length=12)),
                ('amount', models.IntegerField(default=50, validators=[cart.models.Cart.validate_gt_fifty, cart.models.Cart.validate_lt_fifteenhundred])),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='issues.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
