# Generated by Django 2.2.2 on 2019-07-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='feature_id',
            field=models.IntegerField(default=None),
        ),
    ]
