# Generated by Django 2.2.2 on 2019-07-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_feature_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='feature_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
